CorporationX/account_service

src/main/java/faang/school/accountservice/entity/AccountNumberSequence.java, src/main/java/faang/school/accountservice/entity/FreeAccountId.java, src/main/java/faang/school/accountservice/entity/FreeAccountNumber.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/repository/AccountSequenceRepository.java, src/main/java/faang/school/accountservice/repository/FreeAccountRepository.java, src/main/java/faang/school/accountservice/scheduler/AccountNumberScheduler.java, src/main/java/faang/school/accountservice/service/FreeAccountNumberService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V003__create_free_account_numbers.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/service/FreeAccountNumberServiceTest.java
- создал сервис для управления уникальными номерами счетов
- написал тесты
=> Feature bc 5760

src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/controller/BalanceAuditController.java, src/main/java/faang/school/accountservice/controller/BalanceController.java, src/main/java/faang/school/accountservice/dto/BalanceAuditDto.java, src/main/java/faang/school/accountservice/dto/BalanceDto.java, src/main/java/faang/school/accountservice/dto/UpdateBalanceDto.java, src/main/java/faang/school/accountservice/mapper/BalanceAuditMapper.java, src/main/java/faang/school/accountservice/mapper/BalanceMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Balance.java, src/main/java/faang/school/accountservice/model/BalanceAudit.java, src/main/java/faang/school/accountservice/repository/BalanceAuditRepository.java, src/main/java/faang/school/accountservice/repository/BalanceRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/service/BalanceAuditService.java, src/main/java/faang/school/accountservice/service/BalanceService.java, src/main/resources/db/changelog/changeset/V002__account-service_balance.sql, src/main/resources/db/changelog/changeset/V003__account-service_balance_audit.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/service/BalanceAuditServiceTest.java
Добавил сохранение истории изменения баланс аккаунта. Часть кода связанного с Balance взял отсюда feature-BC-6063-rebuild-task. Мануально проверил все работает. Тесты отдельно таску сделаю
=> Баланс история

src/main/java/faang/school/accountservice/enums/AccountStatus.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/enums/OwnerType.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Owner.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/main/resources/db/changelog/changeset/account_V001__create.sql, src/main/resources/db/changelog/db.changelog-master.yaml
=> add new entity and migrations

src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/enums/account/AccountStatus.java, src/main/java/faang/school/accountservice/enums/account/AccountType.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Balance.java, src/main/java/faang/school/accountservice/model/owner/Owner.java, src/main/java/faang/school/accountservice/model/owner/OwnerType.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/main/resources/db/changelog/changeset/V001_create_accounts_table.sql, src/main/resources/db/changelog/changeset/V002_create_owners_table.sql, src/main/resources/db/changelog/changeset/V003_create_balance_table.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Добавил модель данных Account и связанные с ней сущности.
Создал скрипты для создания необходимых БД и для индекса на поиск аккаунтов, принадлежащие определенным пользователям
=> Создание платежного счета - part 1

src/main/resources/db/changelog/changeset/V003_balance_init.sql
feature-15561. Написал миграцию для создания таблицы balance, для задачи “Работа с балансами“.
=> feature-15561. Написал миграцию для создания таблицы balance, для задачи “Работа с балансами“.

src/main/java/faang/school/accountservice/mapper/BalanceAuditMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Balance.java, src/main/java/faang/school/accountservice/model/BalanceAudit.java, src/main/java/faang/school/accountservice/repository/BalanceAuditRepository.java, src/main/java/faang/school/accountservice/service/BalanceServiceImpl.java, src/main/resources/db/changelog/changeset/V005_create_balance_audit_table.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/mapper/BalanceAuditMapperTest.java, src/test/java/faang/school/accountservice/mapper/BalanceMapperTest.java, src/test/java/faang/school/accountservice/service/BalanceServiceImplTest.java
=> BJS2-11705

src/main/java/faang/school/accountservice/controller/FreeAccountNumbersController.java, src/main/java/faang/school/accountservice/dto/FreeAccountNumberDto.java, src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java, src/test/java/faang/school/accountservice/integration/service/FreeAccountNumbersServiceIntegrationTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-11719
Генерация уникальных номеров счетов
=> BJS2-11719: Generating unique account numbers

src/main/java/faang/school/accountservice/dto/AccountDto.java, src/main/java/faang/school/accountservice/jpa/BalanceJpaRepository.java, src/main/java/faang/school/accountservice/mapper/AccountMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Balance.java, src/main/java/faang/school/accountservice/repository/BalanceRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/service/BalanceService.java, src/main/resources/db/changelog/changeset/V004__account-service_balance.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/service/AccountServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-11723
Работа с балансами
=> BJS2-11723: Working with balances

.github/workflows/ci.yml, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/BalanceAuditDto.java, src/main/java/faang/school/accountservice/enums/Operation.java, src/main/java/faang/school/accountservice/mapper/BalanceAuditMapper.java, src/main/java/faang/school/accountservice/model/BalanceAudit.java, src/main/java/faang/school/accountservice/repository/BalanceAuditRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V005__account-service_audit-balance.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/service/AccountServiceTest.java
Task: https://faang-school.atlassian.net/browse/BJS2-11724
Balance audit
=> BJS2-11724: Balance audit

.github/workflows/ci.yml, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/AccountDto.java, src/main/java/faang/school/accountservice/dto/UpdateAccountDto.java, src/main/java/faang/school/accountservice/enums/AccountStatus.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/enums/OwnerType.java, src/main/java/faang/school/accountservice/exception/DataValidationException.java, src/main/java/faang/school/accountservice/mapper/AccountMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/repository/AccountRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/validator/AccountValidator.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/main/resources/db/changelog/changeset/V002__account-service_account_index.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/AccountServiceTest.java
Implemented Data base migration, AccountService, AccountController and CI.
All checked.  Unit tests - done.
=> Создание платежного счета

src/main/java/faang/school/accountservice/client/ProjectServiceClient.java, src/main/java/faang/school/accountservice/client/UserServiceClient.java, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/AccountDto.java, src/main/java/faang/school/accountservice/dto/ErrorResponseDto.java, src/main/java/faang/school/accountservice/dto/ProjectDto.java, src/main/java/faang/school/accountservice/dto/UserDto.java, src/main/java/faang/school/accountservice/enums/AccountStatus.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/exception/EntityNotFoundException.java, src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java, src/main/java/faang/school/accountservice/exception/IllegalEntityException.java, src/main/java/faang/school/accountservice/mapper/AccountMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/repository/AccountRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/validator/AccountValidator.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/test/java/faang/school/accountservice/service/AccountServiceTest.java, src/test/java/faang/school/accountservice/validator/AccountValidatorTest.java
- Created `Account` entity and corresponding JPA repository for database interaction.
- Added `AccountController` to handle account-related HTTP requests, including opening, freezing, and closing accounts.
- Developed `AccountService` to encapsulate business logic, including methods for getting, opening, freezing, and closing accounts.
- Implemented `AccountMapper` using MapStruct to convert between `Account` entities and `AccountDto` data transfer objects.
- Introduced `AccountValidator` to ensure that either `userId` or `projectId` is provided and valid during account creation.
- Added unit tests for `AccountService` and `AccountValidator` to ensure correctness of operations.
- Created `AccountStatus`, `AccountType`, and `Currency` enums for type safety in the `Account` entity.
- …
=> BJS2-25875 - Создание платежного счета

src/main/resources/db/changelog/changeset/V002__account-service_account.sql, src/main/resources/db/changelog/db.changelog-master.yaml
- Добавлана миграция на создания таблицы, отражающую сущность Balance (Таблица account пока не создана в этой задаче)
=> BJS2-25874

build.gradle.kts, src/main/java/faang/school/accountservice/AccountServiceApplication.java, src/main/java/faang/school/accountservice/config/account/AccountGenerateConfig.java, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/UpdateAccountDto.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/AccountNumberSequence.java, src/main/java/faang/school/accountservice/model/FreeAccountNumber.java, src/main/java/faang/school/accountservice/model/FreeAccountNumberId.java, src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java, src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java, src/main/java/faang/school/accountservice/scheduler/account/AccountGenerationScheduler.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/service/FreeAccountNumbersGenerationService.java, src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V003__account-service_account_free_account.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/AccountServiceTest.java, src/test/java/faang/school/accountservice/FreeAccountNumbersServiceTest.java, src/test/resources/init.sql
=> Управление уникальными номерами счетов + Генерация уникальных номеров счетов

build.gradle.kts, src/main/java/faang/school/accountservice/AccountServiceApplication.java, src/main/java/faang/school/accountservice/cache/AbstractFreeAccountNumbersCache.java, src/main/java/faang/school/accountservice/cache/CompanyFreeAccountNumbersCache.java, src/main/java/faang/school/accountservice/cache/FreeAccountNumbersCache.java, src/main/java/faang/school/accountservice/cache/IndividualFreeAccountNumbersCache.java, src/main/java/faang/school/accountservice/config/cache/AbstractAccountCacheConfig.java, src/main/java/faang/school/accountservice/config/cache/CompanyAccountCacheConfig.java, src/main/java/faang/school/accountservice/config/cache/IndividualAccountCacheConfig.java, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/AccountDto.java, src/main/java/faang/school/accountservice/entity/Account.java, src/main/java/faang/school/accountservice/entity/AccountOwner.java, src/main/java/faang/school/accountservice/entity/Balance.java, src/main/java/faang/school/accountservice/enums/AccountStatus.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/enums/OwnerType.java, src/main/java/faang/school/accountservice/mapper/AccountMapper.java, src/main/java/faang/school/accountservice/repository/AccountOwnerRepository.java, src/main/java/faang/school/accountservice/repository/AccountRepository.java, src/main/java/faang/school/accountservice/repository/BalanceRepository.java, src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java, src/main/java/faang/school/accountservice/service/AccountOwnerService.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/service/BalanceService.java, src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java, src/main/resources/application.yaml, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/main/resources/db/changelog/changeset/V001__account-service_account_balance_sequences.sql, src/main/resources/db/changelog/db.changelog-master.yaml
BJS2-25833
BJS2-25834
BJS2-25838
=> Tasks BJS2-25833 BJS2-25834 BJS2-25838

src/main/java/faang/school/accountservice/enums/AccountStatus.java, src/main/java/faang/school/accountservice/enums/AccountType.java, src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/enums/OwnerType.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/AccountOwner.java, src/main/java/faang/school/accountservice/repository/AccountOwnerRepository.java, src/main/java/faang/school/accountservice/repository/AccountRepository.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql
Описал сущность Account в соответствии с задачей https://faang-school.atlassian.net/browse/BJS2-27510, написал миграции. Решил вынести владельцев счета в отдельную таблицу, для того, чтобы не хранить дублирующиеся данные, сделал пару (owner_id, owner_type) уникальными, чтобы предотврадить возможность дублирования этой записи в таблице. для упрощения поиска по владельцу сделал индекс по owner_id в таблице accounts и индекс по уникальной паре (owner_id, owner_type) в accounts_owners. еще прикреплю схемку, может кому-то так проще будет
=> BJS2-27510 initial commit

src/main/java/faang/school/accountservice/config/generator/AccountNumberGenerator.java, src/main/java/faang/school/accountservice/controller/AccountController.java, src/main/java/faang/school/accountservice/dto/Error.java, src/main/java/faang/school/accountservice/enums/Currency.java, src/main/java/faang/school/accountservice/exception/ErrorResponse.java, src/main/java/faang/school/accountservice/exception/GlobalExceptionHandler.java, src/main/java/faang/school/accountservice/mapper/AccountMapper.java, src/main/java/faang/school/accountservice/model/dto/AccountDto.java, src/main/java/faang/school/accountservice/model/dto/Money.java, src/main/java/faang/school/accountservice/model/entity/Account.java, src/main/java/faang/school/accountservice/model/enums/AccountStatus.java, src/main/java/faang/school/accountservice/model/enums/AccountType.java, src/main/java/faang/school/accountservice/model/enums/Currency.java, src/main/java/faang/school/accountservice/model/enums/OwnerType.java, src/main/java/faang/school/accountservice/repository/AccountRepository.java, src/main/java/faang/school/accountservice/service/AccountService.java, src/main/java/faang/school/accountservice/service/impl/AccountServiceImpl.java, src/main/java/faang/school/accountservice/validator/AccountValidator.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/test/java/faang/school/accountservice/integration/IntegrationTestBase.java, src/test/java/faang/school/accountservice/integration/annotation/IT.java, src/test/java/faang/school/accountservice/integration/controller/AccountControllerIT.java, src/test/java/faang/school/accountservice/integration/repository/AccountRepositoryIT.java, src/test/java/faang/school/accountservice/service/impl/AccountServiceImplTest.java, src/test/java/faang/school/accountservice/validator/AccountValidatorTest.java, src/test/resources/application-test.yaml, src/test/resources/sql/data.sql
Генератор номера счета сделал для удобства, на сколько понял это другая таска
Также нужно будет произвести интеграцию с балансом
=> BJS2-26749 Создание платежного счета

build.gradle.kts, src/main/java/faang/school/accountservice/exception/ErrorResponse.java, src/main/java/faang/school/accountservice/model/dto/Error.java, src/main/java/faang/school/accountservice/model/dto/Money.java, src/main/java/faang/school/accountservice/model/entity/AccountNumberSequence.java, src/main/java/faang/school/accountservice/model/entity/FreeAccountNumber.java, src/main/java/faang/school/accountservice/model/entity/FreeAccountNumberId.java, src/main/java/faang/school/accountservice/model/enums/AccountType.java, src/main/java/faang/school/accountservice/model/enums/Currency.java, src/main/java/faang/school/accountservice/repository/AccountNumbersSequenceRepository.java, src/main/java/faang/school/accountservice/repository/FreeAccountNumbersRepository.java, src/main/java/faang/school/accountservice/service/FreeAccountNumbersService.java, src/main/java/faang/school/accountservice/service/impl/account/number/FreeAccountNumbersServiceImpl.java, src/main/resources/db/changelog/changeset/V001__account-service_account.sql, src/main/resources/db/changelog/changeset/V002_account-service_numbers.sql, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/faang/school/accountservice/IntegrationBaseTest.java, src/test/java/faang/school/accountservice/integration/annotation/IT.java, src/test/java/faang/school/accountservice/integration/service/FreeAccountNumbersServiceImplTest.java, src/test/resources/application-test.yaml, src/test/resources/sql/data.sql
Таска Андрея зависит от моей, поэтому, наверное, лучше мерджить сначала его в мою(только я сначала вмерджу себе мастер, а потом он уже себя, чтобы решил свои потенциальные конфликты)
=> Feature bjs2 26752 Управление уникальными номерами счетов

src/main/java/faang/school/accountservice/dto/BalanceDto.java, src/main/java/faang/school/accountservice/mappers/BalanceMapper.java, src/main/java/faang/school/accountservice/model/Account.java, src/main/java/faang/school/accountservice/model/Balance.java, src/main/java/faang/school/accountservice/repository/BalanceRepository.java, src/main/resources/db/changelog/changeset/V003__acount-service_create_balance_table.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Created migration V003, included,
Created Balance Model, DTO, Mapper and Repository. Added Balance to Account Model.
=> Работа с балансами BJS2-41996

src/main/java/faang/school/accountservice/enums/Currency.java, src/main/resources/db/changelog/changeset/V002_account-service_added_account_currency_table.sql, src/main/resources/db/changelog/db.changelog-master.yaml
Adds migration of Account table;
Adds migration of Currency table.
=> BJS2-41943 Feature / Account Service / Account, Currency tables migration

src/main/resources/db/changelog/changeset/V001__account-service_account.sql
Написать миграцию для создания таблицы account, который будет описывать все поля, перечисленные в условиях задачи, с подходящими и оптимальными типами данных и содержать первичный ключ. Миграцию необходимо сделать в отдельной задаче и PR и как можно быстрее замерджить.
=> BJS2-41982 Миграция в рамках задачи "Создание платежного счета"
